titles = ["SQL Tutorial", "SQL Introduction", "SQL Syntax", "SQL SELECT Statement", "SQL SELECT DISTINCT Statement",
          "SQL WHERE Clause", "SQL AND, OR, NOT Operators", "SQL ORDER BY Keyword", "SQL INSERT INTO Statement",
          "SQL NULL Values - IS NULL and IS NOT NULL", "SQL UPDATE Statement", "SQL DELETE Statement", "SQL SELECT TOP, LIMIT, ROWNUM",
          "SQL MIN() and MAX() Functions", "SQL COUNT(), AVG() and SUM() Functions", "SQL LIKE Operator", "SQL Wildcard Characters",
          "SQL IN Operator", "SQL BETWEEN Operator", "SQL Aliases", "SQL Joins", "SQL INNER JOIN Keyword", "SQL LEFT JOIN Keyword",
          "SQL RIGHT JOIN Keyword", "SQL FULL OUTER JOIN Keyword", "SQL Self JOIN", "SQL UNION Operator", "SQL GROUP BY Statement",
          "SQL HAVING Clause", "SQL EXISTS Operator", "SQL ANY and ALL Operators", "SQL SELECT INTO Statement", "SQL INSERT INTO SELECT Statement",
          "SQL CASE Statement", "SQL ISNULL(), NVL(), IFNULL() and COALESCE() Functions", "SQL Stored Procedures", "SQL Comments",
          "SQL CREATE DATABASE Statement"
          ]

urls = ['https://www.w3schools.com/sql/default.asp', 'https://www.w3schools.com/sql/sql_intro.asp', 'https://www.w3schools.com/sql/sql_syntax.asp',
        'https://www.w3schools.com/sql/sql_select.asp', 'https://www.w3schools.com/sql/sql_distinct.asp', 'https://www.w3schools.com/sql/sql_where.asp',
        'https://www.w3schools.com/sql/sql_and_or.asp', 'https://www.w3schools.com/sql/sql_orderby.asp', 'https://www.w3schools.com/sql/sql_insert.asp',
        'https://www.w3schools.com/sql/sql_null_values.asp', 'https://www.w3schools.com/sql/sql_update.asp', 'https://www.w3schools.com/sql/sql_delete.asp',
        'https://www.w3schools.com/sql/sql_top.asp', 'https://www.w3schools.com/sql/sql_min_max.asp', 'https://www.w3schools.com/sql/sql_count_avg_sum.asp',
        'https://www.w3schools.com/sql/sql_like.asp', 'https://www.w3schools.com/sql/sql_wildcards.asp', 'https://www.w3schools.com/sql/sql_in.asp',
        'https://www.w3schools.com/sql/sql_between.asp', 'https://www.w3schools.com/sql/sql_alias.asp', 'https://www.w3schools.com/sql/sql_join.asp',
        'https://www.w3schools.com/sql/sql_join_inner.asp', 'https://www.w3schools.com/sql/sql_join_left.asp', 'https://www.w3schools.com/sql/sql_join_right.asp',
        'https://www.w3schools.com/sql/sql_join_full.asp', 'https://www.w3schools.com/sql/sql_join_self.asp', 'https://www.w3schools.com/sql/sql_union.asp',
        'https://www.w3schools.com/sql/sql_groupby.asp', 'https://www.w3schools.com/sql/sql_having.asp', 'https://www.w3schools.com/sql/sql_exists.asp',
        'https://www.w3schools.com/sql/sql_any_all.asp', 'https://www.w3schools.com/sql/sql_select_into.asp', 'https://www.w3schools.com/sql/sql_insert_into_select.asp',
        'https://www.w3schools.com/sql/sql_case.asp', 'https://www.w3schools.com/sql/sql_isnull.asp', 'https://www.w3schools.com/sql/sql_stored_procedures.asp',
        'https://www.w3schools.com/sql/sql_comments.asp'
        ]

sql_query_examples = [('SELECT * FROM Customers;', 'https://www.w3schools.com/sql/default.asp'),
                      ('SELECT * FROM Customers;', 'https://www.w3schools.com/sql/sql_intro.asp'),
                      ('SELECT * FROM Customers;', 'https://www.w3schools.com/sql/sql_syntax.asp'),
                      ('SELECT CustomerName, City FROM Customers;', 'https://www.w3schools.com/sql/sql_select.asp'),
                      ('SELECT * FROM Customers;', 'https://www.w3schools.com/sql/sql_select.asp'),
                      ('SELECT Country FROM Customers;', 'https://www.w3schools.com/sql/sql_distinct.asp'),
                      ('SELECT DISTINCT Country FROM Customers;', 'https://www.w3schools.com/sql/sql_distinct.asp'),
                      ('SELECT COUNT(DISTINCT Country) FROM Customers;', 'https://www.w3schools.com/sql/sql_distinct.asp'),
                      ('SELECT Count(*) AS DistinctCountries FROM (SELECT DISTINCT Country FROM Customers);', 'https://www.w3schools.com/sql/sql_distinct.asp'),
                      ("SELECT * FROM Customers WHERE Country='Mexico';", 'https://www.w3schools.com/sql/sql_where.asp'),
                      ('SELECT * FROM Customers WHERE CustomerID=1;', 'https://www.w3schools.com/sql/sql_where.asp'),
                      ("SELECT * FROM Customers WHERE Country='Germany' AND City='Berlin';", 'https://www.w3schools.com/sql/sql_and_or.asp'),
                      ("SELECT * FROM Customers WHERE City='Berlin' OR City='München';", 'https://www.w3schools.com/sql/sql_and_or.asp'),
                      ("SELECT * FROM Customers WHERE Country='Germany' OR Country='Spain';", 'https://www.w3schools.com/sql/sql_and_or.asp'),
                      ("SELECT * FROM Customers WHERE NOT Country='Germany';", 'https://www.w3schools.com/sql/sql_and_or.asp'),
                      ("SELECT * FROM Customers WHERE Country='Germany' AND (City='Berlin' OR City='München');", 'https://www.w3schools.com/sql/sql_and_or.asp'),
                      ("SELECT * FROM Customers WHERE NOT Country='Germany' AND NOT Country='USA';", 'https://www.w3schools.com/sql/sql_and_or.asp'),
                      ('SELECT * FROM Customers ORDER BY Country;', 'https://www.w3schools.com/sql/sql_orderby.asp'),
                      ('SELECT * FROM Customers ORDER BY Country DESC;', 'https://www.w3schools.com/sql/sql_orderby.asp'),
                      ('SELECT * FROM Customers ORDER BY Country, CustomerName;', 'https://www.w3schools.com/sql/sql_orderby.asp'),
                      ('SELECT * FROM Customers ORDER BY Country ASC, CustomerName DESC;', 'https://www.w3schools.com/sql/sql_orderby.asp'),
                      ("INSERT INTO Customers (CustomerName, ContactName, Address, City, PostalCode, Country) VALUES ('Cardinal', 'Tom B. Erichsen', 'Skagen 21', 'Stavanger', '4006', 'Norway');", 'https://www.w3schools.com/sql/sql_insert.asp'),
                      ("INSERT INTO Customers (CustomerName, City, Country) VALUES ('Cardinal', 'Stavanger', 'Norway');", 'https://www.w3schools.com/sql/sql_insert.asp'),
                      ('SELECT CustomerName, ContactName, Address FROM Customers WHERE Address IS NULL;', 'https://www.w3schools.com/sql/sql_null_values.asp'),
                      ('SELECT CustomerName, ContactName, Address FROM Customers WHERE Address IS NOT NULL;', 'https://www.w3schools.com/sql/sql_null_values.asp'),
                      ("UPDATE Customers SET ContactName = 'Alfred Schmidt', City= 'Frankfurt' WHERE CustomerID = 1;", 'https://www.w3schools.com/sql/sql_update.asp'),
                      ("UPDATE Customers SET ContactName='Juan' WHERE Country='Mexico';", 'https://www.w3schools.com/sql/sql_update.asp'),
                      ("UPDATE Customers SET ContactName='Juan';", 'https://www.w3schools.com/sql/sql_update.asp'),
                      ("DELETE FROM Customers WHERE CustomerName='Alfreds Futterkiste';", 'https://www.w3schools.com/sql/sql_delete.asp'),
                      ('DELETE FROM Customers;', 'https://www.w3schools.com/sql/sql_delete.asp'),
                      ('SELECT TOP 3 * FROM Customers;', 'https://www.w3schools.com/sql/sql_top.asp'),
                      ('SELECT * FROM Customers LIMIT 3;', 'https://www.w3schools.com/sql/sql_top.asp'),
                      ('SELECT TOP 50 PERCENT * FROM Customers;', 'https://www.w3schools.com/sql/sql_top.asp'),
                      ("SELECT TOP 3 * FROM Customers WHERE Country='Germany';", 'https://www.w3schools.com/sql/sql_top.asp'),
                      ("SELECT * FROM Customers WHERE Country='Germany' LIMIT 3;", 'https://www.w3schools.com/sql/sql_top.asp'),
                      ('SELECT MIN(Price) AS SmallestPrice FROM Products;', 'https://www.w3schools.com/sql/sql_min_max.asp'),
                      ('SELECT MAX(Price) AS LargestPrice FROM Products;', 'https://www.w3schools.com/sql/sql_min_max.asp'),
                      ('SELECT COUNT(ProductID) FROM Products;', 'https://www.w3schools.com/sql/sql_count_avg_sum.asp'),
                      ('SELECT AVG(Price) FROM Products;', 'https://www.w3schools.com/sql/sql_count_avg_sum.asp'),
                      ('SELECT SUM(Quantity) FROM OrderDetails;', 'https://www.w3schools.com/sql/sql_count_avg_sum.asp'),
                      ("SELECT * FROM Customers WHERE CustomerName LIKE 'a%';", 'https://www.w3schools.com/sql/sql_like.asp'),
                      ("SELECT * FROM Customers WHERE CustomerName LIKE '%a';", 'https://www.w3schools.com/sql/sql_like.asp'),
                      ("SELECT * FROM Customers WHERE CustomerName LIKE '%or%';", 'https://www.w3schools.com/sql/sql_like.asp'),
                      ("SELECT * FROM Customers WHERE CustomerName LIKE '_r%';", 'https://www.w3schools.com/sql/sql_like.asp'),
                      ("SELECT * FROM Customers WHERE CustomerName LIKE 'a__%';", 'https://www.w3schools.com/sql/sql_like.asp'),
                      ("SELECT * FROM Customers WHERE ContactName LIKE 'a%o';", 'https://www.w3schools.com/sql/sql_like.asp'),
                      ("SELECT * FROM Customers WHERE CustomerName NOT LIKE 'a%';", 'https://www.w3schools.com/sql/sql_like.asp'),
                      ("SELECT * FROM Customers WHERE City LIKE 'ber%';", 'https://www.w3schools.com/sql/sql_wildcards.asp'),
                      ("SELECT * FROM Customers WHERE City LIKE '%es%';", 'https://www.w3schools.com/sql/sql_wildcards.asp'),
                      ("SELECT * FROM Customers WHERE City LIKE '_ondon';", 'https://www.w3schools.com/sql/sql_wildcards.asp'),
                      ("SELECT * FROM Customers WHERE City LIKE 'L_n_on';", 'https://www.w3schools.com/sql/sql_wildcards.asp'),
                      ("SELECT * FROM Customers WHERE City LIKE '[bsp]%';", 'https://www.w3schools.com/sql/sql_wildcards.asp'),
                      ("SELECT * FROM Customers WHERE City LIKE '[a-c]%';", 'https://www.w3schools.com/sql/sql_wildcards.asp'),
                      ("SELECT * FROM Customers WHERE City LIKE '[!bsp]%';", 'https://www.w3schools.com/sql/sql_wildcards.asp'),
                      ("SELECT * FROM Customers WHERE City NOT LIKE '[bsp]%';", 'https://www.w3schools.com/sql/sql_wildcards.asp'),
                      ("SELECT * FROM Customers WHERE Country IN ('Germany', 'France', 'UK');", 'https://www.w3schools.com/sql/sql_in.asp'),
                      ("SELECT * FROM Customers WHERE Country NOT IN ('Germany', 'France', 'UK');", 'https://www.w3schools.com/sql/sql_in.asp'),
                      ('SELECT * FROM Customers WHERE Country IN (SELECT Country FROM Suppliers);', 'https://www.w3schools.com/sql/sql_in.asp'),
                      ('SELECT * FROM Products WHERE Price BETWEEN 10 AND 20;', 'https://www.w3schools.com/sql/sql_between.asp'),
                      ('SELECT * FROM Products WHERE Price NOT BETWEEN 10 AND 20;', 'https://www.w3schools.com/sql/sql_between.asp'),
                      ('SELECT * FROM Products WHERE Price BETWEEN 10 AND 20 AND CategoryID NOT IN (1,2,3);', 'https://www.w3schools.com/sql/sql_between.asp'),
                      ("SELECT * FROM Products WHERE ProductName BETWEEN 'Carnarvon Tigers' AND 'Mozzarella di Giovanni' ORDER BY ProductName;", 'https://www.w3schools.com/sql/sql_between.asp'),
                      ('SELECT * FROM Products WHERE ProductName BETWEEN "Carnarvon Tigers" AND "Chef Anton\'s Cajun Seasoning" ORDER BY ProductName;', 'https://www.w3schools.com/sql/sql_between.asp'),
                      ("SELECT * FROM Products WHERE ProductName NOT BETWEEN 'Carnarvon Tigers' AND 'Mozzarella di Giovanni' ORDER BY ProductName;", 'https://www.w3schools.com/sql/sql_between.asp'),
                      ('SELECT * FROM Orders WHERE OrderDate BETWEEN #01/07/1996# AND #31/07/1996#;', 'https://www.w3schools.com/sql/sql_between.asp'),
                      ("SELECT * FROM Orders WHERE OrderDate BETWEEN '1996-07-01' AND '1996-07-31';", 'https://www.w3schools.com/sql/sql_between.asp'),
                      ('SELECT CustomerID AS ID, CustomerName AS Customer FROM Customers;', 'https://www.w3schools.com/sql/sql_alias.asp'),
                      ('SELECT CustomerName AS Customer, ContactName AS [Contact Person] FROM Customers;', 'https://www.w3schools.com/sql/sql_alias.asp'),
                      ("SELECT CustomerName, Address + ', ' + PostalCode + ' ' + City + ', ' + Country AS Address FROM Customers;", 'https://www.w3schools.com/sql/sql_alias.asp'),
                      ('SELECT o.OrderID, o.OrderDate, c.CustomerName FROM Customers AS c, Orders AS o WHERE c.CustomerName="Around the Horn" AND c.CustomerID=o.CustomerID;', 'https://www.w3schools.com/sql/sql_alias.asp'),
                      ('SELECT Orders.OrderID, Orders.OrderDate, Customers.CustomerName FROM Customers, Orders WHERE Customers.CustomerName="Around the Horn" AND Customers.CustomerID=Orders.CustomerID;', 'https://www.w3schools.com/sql/sql_alias.asp'),
                      ('SELECT Orders.OrderID, Customers.CustomerName, Orders.OrderDate FROM Orders INNER JOIN Customers ON Orders.CustomerID=Customers.CustomerID;', 'https://www.w3schools.com/sql/sql_join.asp'),
                      ('SELECT Orders.OrderID, Customers.CustomerName FROM Orders INNER JOIN Customers ON Orders.CustomerID = Customers.CustomerID;', 'https://www.w3schools.com/sql/sql_join_inner.asp'),
                      ('SELECT Orders.OrderID, Customers.CustomerName, Shippers.ShipperName FROM ((Orders INNER JOIN Customers ON Orders.CustomerID = Customers.CustomerID) INNER JOIN Shippers ON Orders.ShipperID = Shippers.ShipperID);', 'https://www.w3schools.com/sql/sql_join_inner.asp'),
                      ('SELECT Customers.CustomerName, Orders.OrderID FROM Customers LEFT JOIN Orders ON Customers.CustomerID = Orders.CustomerID ORDER BY Customers.CustomerName;', 'https://www.w3schools.com/sql/sql_join_left.asp'),
                      ('SELECT Orders.OrderID, Employees.LastName, Employees.FirstName FROM Orders RIGHT JOIN Employees ON Orders.EmployeeID = Employees.EmployeeID ORDER BY Orders.OrderID;', 'https://www.w3schools.com/sql/sql_join_right.asp'),
                      ('SELECT A.CustomerName AS CustomerName1, B.CustomerName AS CustomerName2, A.City FROM Customers A, Customers B WHERE A.CustomerID <> B.CustomerID AND A.City = B.City ORDER BY A.City;', 'https://www.w3schools.com/sql/sql_join_self.asp'),
                      ('SELECT City FROM Customers UNION SELECT City FROM Suppliers ORDER BY City;', 'https://www.w3schools.com/sql/sql_union.asp'),
                      ('SELECT City FROM Customers UNION ALL SELECT City FROM Suppliers ORDER BY City;', 'https://www.w3schools.com/sql/sql_union.asp'),
                      ("SELECT City, Country FROM Customers WHERE Country='Germany' UNION SELECT City, Country FROM Suppliers WHERE Country='Germany' ORDER BY City;", 'https://www.w3schools.com/sql/sql_union.asp'),
                      ("SELECT City, Country FROM Customers WHERE Country='Germany' UNION ALL SELECT City, Country FROM Suppliers WHERE Country='Germany' ORDER BY City;", 'https://www.w3schools.com/sql/sql_union.asp'),
                      ("SELECT 'Customer' As Type, ContactName, City, Country FROM Customers UNION SELECT 'Supplier', ContactName, City, Country FROM Suppliers;", 'https://www.w3schools.com/sql/sql_union.asp'),
                      ('SELECT COUNT(CustomerID), Country FROM Customers GROUP BY Country;', 'https://www.w3schools.com/sql/sql_groupby.asp'),
                      ('SELECT COUNT(CustomerID), Country FROM Customers GROUP BY Country ORDER BY COUNT(CustomerID) DESC;', 'https://www.w3schools.com/sql/sql_groupby.asp'),
                      ('SELECT Shippers.ShipperName, COUNT(Orders.OrderID) AS NumberOfOrders FROM Orders LEFT JOIN Shippers ON Orders.ShipperID = Shippers.ShipperID GROUP BY ShipperName;', 'https://www.w3schools.com/sql/sql_groupby.asp'),
                      ('SELECT COUNT(CustomerID), Country FROM Customers GROUP BY Country HAVING COUNT(CustomerID) > 5;', 'https://www.w3schools.com/sql/sql_having.asp'),
                      ('SELECT COUNT(CustomerID), Country FROM Customers GROUP BY Country HAVING COUNT(CustomerID) > 5 ORDER BY COUNT(CustomerID) DESC;', 'https://www.w3schools.com/sql/sql_having.asp'),
                      ('SELECT Employees.LastName, COUNT(Orders.OrderID) AS NumberOfOrders FROM (Orders INNER JOIN Employees ON Orders.EmployeeID = Employees.EmployeeID) GROUP BY LastName HAVING COUNT(Orders.OrderID) > 10;', 'https://www.w3schools.com/sql/sql_having.asp'),
                      ("SELECT Employees.LastName, COUNT(Orders.OrderID) AS NumberOfOrders FROM Orders INNER JOIN Employees ON Orders.EmployeeID = Employees.EmployeeID WHERE LastName = 'Davolio' OR LastName = 'Fuller' GROUP BY LastName HAVING COUNT(Orders.OrderID) > 25;", 'https://www.w3schools.com/sql/sql_having.asp'),
                      ('SELECT SupplierName FROM Suppliers WHERE EXISTS (SELECT ProductName FROM Products WHERE Products.SupplierID = Suppliers.supplierID AND Price < 20);', 'https://www.w3schools.com/sql/sql_exists.asp'),
                      ('SELECT SupplierName FROM Suppliers WHERE EXISTS (SELECT ProductName FROM Products WHERE Products.SupplierID = Suppliers.supplierID AND Price = 22);', 'https://www.w3schools.com/sql/sql_exists.asp'),
                      ('SELECT ProductName FROM Products WHERE ProductID = ANY (SELECT ProductID FROM OrderDetails WHERE Quantity = 10);', 'https://www.w3schools.com/sql/sql_any_all.asp'),
                      ('SELECT ProductName FROM Products WHERE ProductID = ANY (SELECT ProductID FROM OrderDetails WHERE Quantity > 99);', 'https://www.w3schools.com/sql/sql_any_all.asp'),
                      ('SELECT ProductName FROM Products WHERE ProductID = ALL (SELECT ProductID FROM OrderDetails WHERE Quantity = 10);', 'https://www.w3schools.com/sql/sql_any_all.asp'),
                      ('INSERT INTO Customers (CustomerName, City, Country) SELECT SupplierName, City, Country FROM Suppliers;', 'https://www.w3schools.com/sql/sql_insert_into_select.asp'),
                      ('INSERT INTO Customers (CustomerName, ContactName, Address, City, PostalCode, Country) SELECT SupplierName, ContactName, Address, City, PostalCode, Country FROM Suppliers;', 'https://www.w3schools.com/sql/sql_insert_into_select.asp'),
                      ("INSERT INTO Customers (CustomerName, City, Country) SELECT SupplierName, City, Country FROM Suppliers WHERE Country='Germany';", 'https://www.w3schools.com/sql/sql_insert_into_select.asp'),
                      ('SELECT OrderID, Quantity, CASE WHEN Quantity > 30 THEN "The quantity is greater than 30" WHEN Quantity = 30 THEN "The quantity is 30" ELSE "The quantity is under 30" END AS QuantityText FROM OrderDetails;', 'https://www.w3schools.com/sql/sql_case.asp'),
                      ('SELECT CustomerName, City, Country FROM Customers ORDER BY (CASE WHEN City IS NULL THEN Country ELSE City END);', 'https://www.w3schools.com/sql/sql_case.asp'),
                      ('--Select all: SELECT * FROM Customers;', 'https://www.w3schools.com/sql/sql_comments.asp'),
                      ("SELECT * FROM Customers -- WHERE City='Berlin';", 'https://www.w3schools.com/sql/sql_comments.asp'),
                      ('--SELECT * FROM Customers; SELECT * FROM Products;', 'https://www.w3schools.com/sql/sql_comments.asp'),
                      ('/*Select all the columns of all the records in the Customers table:*/ SELECT * FROM Customers;', 'https://www.w3schools.com/sql/sql_comments.asp'),
                      ('/*SELECT * FROM Customers; SELECT * FROM Products; SELECT * FROM Orders; SELECT * FROM Categories;*/ SELECT * FROM Suppliers;', 'https://www.w3schools.com/sql/sql_comments.asp'),
                      ('SELECT CustomerName, /*City,*/ Country FROM Customers;', 'https://www.w3schools.com/sql/sql_comments.asp'),
                      ("SELECT * FROM Customers WHERE (CustomerName LIKE 'L%' OR CustomerName LIKE 'R%' /*OR CustomerName LIKE 'S%' OR CustomerName LIKE 'T%'*/ OR CustomerName LIKE 'W%') AND Country='USA' ORDER BY CustomerName;", 'https://www.w3schools.com/sql/sql_comments.asp')
                      ]
